/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AsyncCom: typeof import('./src/components/AsyncCom.vue')['default']
    ErrorCom: typeof import('./src/components/ErrorCom.vue')['default']
    LoadingCom: typeof import('./src/components/LoadingCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualList: typeof import('./src/components/VirtualList.vue')['default']
    VirtualListRandom: typeof import('./src/components/VirtualListRandom.vue')['default']
  }
}
